test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,96 +1,76 @@
-name: 'Gensbom: bom'
-description: 'Generates a Software Bill Of Materials (SBOM) from container images and filesystems'
+name: 'tool: installer'
+description: 'Scribe tool installer'
 author: Mikey Strauss
-outputs:
-  output-file:
-    description: 'Bom output file path'
 inputs:
-  type:
-    description: 'Target source type options=[docker,docker-archive, oci-archive, dir, registry]'
-    default: registry
-  target:
-    description: 'Target object name format=[<image:tag>, <dir_path>]'
-    required: true
-  verbose:
-    description: 'Increase verbosity (-v = info, -vv = debug)'
-    default: 1
-  config:
-    description: 'Application config file'
-  format:
-    description: 'Sbom formatter, options=[cyclonedx-json cyclonedx-xml attest-cyclonedx-json statement-cyclonedx-json predicate-cyclonedx-json attest-slsa statement-slsa predicate-slsa]'
-  output-directory:
-    description: 'Report output directory'
-    default: ./scribe/gensbom
-  output-file:
-    description: 'Output result to file'
-  product-key:
-    description: 'Custom/project product key'
-  label:
-    description: 'Custom label'
-  env:
-    description: 'Custom env'
-  filter-regex:
-    description: 'Filter out files by regex'
-  attach-regex:
-    description: 'Attach files content by regex'
-  force:
-    description: 'Force overwrite cache'
-    default: false
-  attest-config:
-    description: 'Attestation config map'
-  attest-name:
-    description: 'Attestation config name (default "gensbom")'
-  attest-default:
-    description: 'Attestation default config, options=[sigstore sigstore-github x509]'
-    default: sigstore-github
-  scribe-enable:
-    description: 'Enable scribe client'
-    default: false
-  scribe-client-id:
-    description: 'Scribe client id' 
-  scribe-client-secret:
-    description: 'Scribe access token' 
-  scribe-url:
-    description: 'Scribe url'
-  scribe-login-url:
-    description: 'Scribe auth login url' 
-  scribe-audience:
-    description: 'Scribe auth audience' 
-  context-dir:
-    description: 'Context dir' 
-  components :
-    description: 'Select sbom components groups, options=[metadata layers packages files dep] (default [metadata,layers,packages,files,dep])'
+  tools:
+    description: 'Select scribe tools <tool:version>'
+    required: false
+    default: 'gensbom,valint'
 
 runs:
-  using: docker
-  image: docker://scribesecuriy.jfrog.io/scribe-docker-public-local/gensbom:latest 
-  args:
-    - bom
-    - ${{ inputs.type }}:${{ inputs.target }}
-    - --verbose=${{ inputs.verbose }}
-    - ${{ inputs.config && '--config=' }}${{ inputs.config }}
-    - ${{ inputs.format && '--format=' }}${{ inputs.format }}
-    - ${{ inputs.product-key && '--product-key=' }}${{ inputs.product-key }}
-    - ${{ inputs.label && '--label=' }}${{ inputs.label }}
-    - ${{ inputs.env && '--env=' }}${{ inputs.env }}
-    - ${{ inputs.filter-regex && '--filter-regex=' }}${{ inputs.filter-regex }}
-    - ${{ inputs.attach-regex && '--attach-regex=' }}${{ inputs.attach-regex }}
-    - --context-type=github
-    - ${{ inputs.output-directory && '--output-directory=' }}${{ inputs.output-directory }}
-    - ${{ inputs.force && '--force=' }}${{ inputs.force }}
-    - ${{ inputs.attest-name && '--attest.name=' }}${{ inputs.attest-name }}
-    - ${{ inputs.attest-default && '--attest.default=' }}${{ inputs.attest-default }}
-    - ${{ inputs.attest-config && '--attest.config=' }}${{ inputs.attest-config }}
-    - ${{ inputs.scribe-enable && '--scribe.enable=' }}${{ inputs.scribe-enable }}
-    - ${{ inputs.scribe-client-id && '--scribe.client-id=' }}${{ inputs.scribe-client-id }}
-    - ${{ inputs.scribe-client-secret && '--scribe.client-secret=' }}${{ inputs.scribe-client-secret }}
-    - ${{ inputs.scribe-url && '--scribe.url=' }}${{ inputs.scribe-url }}
-    - ${{ inputs.scribe-login-url && '--scribe.login-url=' }}${{ inputs.scribe-login-url }}
-    - ${{ inputs.scribe-audience && '--scribe.auth.audience=' }}${{ inputs.scribe-audience }}
-    - ${{ inputs.context-dir && '--scribe.context-dir=' }}${{ inputs.context-dir }}
-    - ${{ inputs.components && '--components=' }}${{ inputs.components }}
+  using: "composite"
+  steps:
+    - name: Installing tool
+      run: |
+        #!/bin/bash
 
+        function install_APT() {
+          TOOLS=$1
+          echo "Installing using APT" ${TOOLS}
+          PLATFORM_SCRIPT="$GITHUB_ACTION_PATH/scripts/$RUNNER_OS.sh"
+          if [ ! -e "$PLATFORM_SCRIPT" ]
+          then
+            echo "$RUNNER_OS OS not supported by installer"
+            exit 1
+          fi
+          . "$PLATFORM_SCRIPT" ${TOOLS} 
+        }
 
+        TOOLS=${{ inputs.tools }}
+        export SCRIBE_TOOLS=${TOOLS//,/ }
+
+        if [[ "${TOOLS}" == "fs-tracker" ]]; then
+          install_APT ${TOOLS}
+        else
+          echo "Installing using install script" ${{ inputs.version }} ${{ inputs.tool }} 
+          export SCRIBE_DEBUG=${DEBUG}
+          export SCRIBE_INSTALL_DIR=/usr/local/bin
+          curl -sSfL https://raw.githubusercontent.com/scribe-security/misc/master/install.sh | sh
+          if [ $? -eq 0 ] ; then
+              echo "Installer success"
+          else 
+              echo "Installer failed"
+              install_APT ${TOOLS}
+          fi
+        fi
+      shell: bash
+
+    - name: Installing tool default config
+      run: |
+        #!/bin/bash
+        set -x
+        TOOLS=${{ inputs.tools }}
+        export SCRIBE_TOOLS=${TOOLS//,/ }
+        for tool in ${SCRIBE_TOOLS}; do
+          DEFAULT_CONFIG="$GITHUB_ACTION_PATH/configs/$tool/$RUNNER_OS.yaml"
+          ls -lhR $GITHUB_ACTION_PATH/configs/
+
+          if [ ! -e "$DEFAULT_CONFIG" ]
+          then
+            echo "$RUNNER_OS Config not supported by installer"
+            exit 0
+          fi
+
+          if [ "$(id --user)" -eq "0" ]; then
+              sudocmd=""
+          else
+              sudocmd="sudo"
+          fi
+          $sudocmd mkdir -p $XDG_CONFIG_HOME/$tool
+          $sudocmd chmod 755 $XDG_CONFIG_HOME/$tool
+          $sudocmd cp $DEFAULT_CONFIG $XDG_CONFIG_HOME/$tool/$tool.yaml
+        done
+      shell: bash
 branding:
   icon: shield
   color: green
